# Generated by Django 4.0.3 on 2022-05-12 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historico', models.TextField(default='Nesta data, às HH:MM, o 9ºGBM foi acionado...')),
                ('data_preenchimento', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('data', models.DateTimeField()),
                ('hora_chamada', models.TimeField()),
                ('hora_no_local', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('nome_preenchedor', models.CharField(max_length=255)),
                ('email_preenchedor', models.EmailField(max_length=255)),
                ('posto_preenchedor', models.CharField(choices=[('SD BM', 'Sd BM'), ('AL CB BM', 'Al Cb BM'), ('CB BM', 'Cb BM'), ('AL SGT BM', 'Al Sgt BM'), ('SGT BM', 'Sgt BM'), ('SUB TEN BM', 'Subten BM'), ('AL OF BM', 'Al Of BM'), ('ASP BM', 'Asp BM'), ('TEN BM', 'Ten BM'), ('CAP BM', 'Cap BM'), ('MAJ BM', 'Maj BM'), ('TC BM', 'Tc BM'), ('CEL BM', 'Cel BM')], default='Sd BM', max_length=255)),
                ('meio_utilizado', models.CharField(choices=[('CICOM', 'Cicom'), ('LINHA DIRETA', 'Linha direta'), ('OUTRO', 'Outro')], default='Cicom', max_length=255)),
                ('situacao', models.CharField(choices=[('COM INTERVENCAO', 'Com intervenção'), ('SI ENGANO', 'S/I Engano'), ('SI TROTE', 'S/I Trote'), ('SI SOLUCIONADO', 'S/I Solucionado')], default='Com intervenção', max_length=250)),
                ('matricula_preenchedor', models.IntegerField()),
                ('tipo_de_utilizacao', models.CharField(choices=[('PRIVADA', 'Privada'), ('PUBLICA', 'Pública'), ('MISTA', 'Mista')], default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=15)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=10)),
                ('solicitante', models.CharField(max_length=255)),
                ('fone', models.CharField(max_length=25, null=True)),
                ('area_preservada', models.BooleanField(default=False)),
                ('caracteristica_local', models.CharField(choices=[('AGROPECUARIO', 'Agropecuário'), ('COMERCIAL', 'Comercial'), ('DE ENSINO', 'De ensino'), ('DE SAUDE', 'De saúde'), ('DE LAZER E/OU CULTURA', 'De lazer e/ou Cultura'), ('DE PRESTAÇAO DE SERVIÇO', 'De prestação de serviço'), ('INDUSTRIAL', 'Industrial'), ('LAGO/AÇUDE', 'Lago/Açude'), ('MONTANHA', 'Montanha'), ('POÇO', 'Poço'), ('RESIDENCIAL', 'Residencial'), ('RIO', 'Rio'), ('RODOVIA/ESTRADA', 'Rodovia/Estrada'), ('TERMINAL DE PASSAGEIRO', 'Terminal de passageiro'), ('TERRENO BALDIO', 'Terreno baldio'), ('VEGETAÇAO', 'Vegetação'), ('VIA PUBLICA URBANA', 'Via pública urbana'), ('OUTRO', 'Outro')], default='Residencial', max_length=255)),
                ('ocorrencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.ocorrencia')),
            ],
        ),
    ]
